{
	"items": [
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/37U9sPqTZMd7AKJCWgcvkt"
						},
						"href": "https://api.spotify.com/v1/artists/37U9sPqTZMd7AKJCWgcvkt",
						"id": "37U9sPqTZMd7AKJCWgcvkt",
						"name": "Pryda",
						"type": "artist",
						"uri": "spotify:artist:37U9sPqTZMd7AKJCWgcvkt"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/4ZjBWKhXRFVVNWSbHZyXTx"
				},
				"href": "https://api.spotify.com/v1/albums/4ZjBWKhXRFVVNWSbHZyXTx",
				"id": "4ZjBWKhXRFVVNWSbHZyXTx",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b2735ed985d3544ccdd2b8b0329c",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e025ed985d3544ccdd2b8b0329c",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d000048515ed985d3544ccdd2b8b0329c",
						"width": 64
					}
				],
				"name": "Layers / Rotonda",
				"release_date": "2013-07-01",
				"release_date_precision": "day",
				"total_tracks": 2,
				"type": "album",
				"uri": "spotify:album:4ZjBWKhXRFVVNWSbHZyXTx"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/37U9sPqTZMd7AKJCWgcvkt"
					},
					"href": "https://api.spotify.com/v1/artists/37U9sPqTZMd7AKJCWgcvkt",
					"id": "37U9sPqTZMd7AKJCWgcvkt",
					"name": "Pryda",
					"type": "artist",
					"uri": "spotify:artist:37U9sPqTZMd7AKJCWgcvkt"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 458746,
			"explicit": false,
			"external_ids": {
				"isrc": "GB6CM1300078"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/6THy6QCDupvNZU6YrCdlkD"
			},
			"href": "https://api.spotify.com/v1/tracks/6THy6QCDupvNZU6YrCdlkD",
			"id": "6THy6QCDupvNZU6YrCdlkD",
			"is_local": false,
			"name": "Rotonda",
			"popularity": 29,
			"preview_url": "https://p.scdn.co/mp3-preview/790dddb37986b0d6016ce7831ca3b61c9d5de761?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 2,
			"type": "track",
			"uri": "spotify:track:6THy6QCDupvNZU6YrCdlkD"
		},
		{
			"album": {
				"album_type": "ALBUM",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/3Om4E4aDBrVJxiBjAnAhO2"
						},
						"href": "https://api.spotify.com/v1/artists/3Om4E4aDBrVJxiBjAnAhO2",
						"id": "3Om4E4aDBrVJxiBjAnAhO2",
						"name": "Paul Jacobs",
						"type": "artist",
						"uri": "spotify:artist:3Om4E4aDBrVJxiBjAnAhO2"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/2oQeCkTKGgySCjpSBPCdRx"
				},
				"href": "https://api.spotify.com/v1/albums/2oQeCkTKGgySCjpSBPCdRx",
				"id": "2oQeCkTKGgySCjpSBPCdRx",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b273bbc8fef9b2835dc96ae592d1",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e02bbc8fef9b2835dc96ae592d1",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d00004851bbc8fef9b2835dc96ae592d1",
						"width": 64
					}
				],
				"name": "Pink Dogs on the Green Grass",
				"release_date": "2021-04-30",
				"release_date_precision": "day",
				"total_tracks": 13,
				"type": "album",
				"uri": "spotify:album:2oQeCkTKGgySCjpSBPCdRx"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/3Om4E4aDBrVJxiBjAnAhO2"
					},
					"href": "https://api.spotify.com/v1/artists/3Om4E4aDBrVJxiBjAnAhO2",
					"id": "3Om4E4aDBrVJxiBjAnAhO2",
					"name": "Paul Jacobs",
					"type": "artist",
					"uri": "spotify:artist:3Om4E4aDBrVJxiBjAnAhO2"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 225249,
			"explicit": false,
			"external_ids": {
				"isrc": "CAZ842000144"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/0W3135lfVN5henzCIdjo2u"
			},
			"href": "https://api.spotify.com/v1/tracks/0W3135lfVN5henzCIdjo2u",
			"id": "0W3135lfVN5henzCIdjo2u",
			"is_local": false,
			"name": "Christopher Robbins",
			"popularity": 41,
			"preview_url": "https://p.scdn.co/mp3-preview/f14f9b55f6d39119f60d7fca83447be844a26411?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:0W3135lfVN5henzCIdjo2u"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/1yz8XixOiIJJ9IxjbnfYV6"
						},
						"href": "https://api.spotify.com/v1/artists/1yz8XixOiIJJ9IxjbnfYV6",
						"id": "1yz8XixOiIJJ9IxjbnfYV6",
						"name": "NewDad",
						"type": "artist",
						"uri": "spotify:artist:1yz8XixOiIJJ9IxjbnfYV6"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/3fsuoXmdJU3QLMNVucfQNE"
				},
				"href": "https://api.spotify.com/v1/albums/3fsuoXmdJU3QLMNVucfQNE",
				"id": "3fsuoXmdJU3QLMNVucfQNE",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b27321012a7e20060d9f876230e4",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e0221012a7e20060d9f876230e4",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d0000485121012a7e20060d9f876230e4",
						"width": 64
					}
				],
				"name": "Waves",
				"release_date": "2021-03-26",
				"release_date_precision": "day",
				"total_tracks": 6,
				"type": "album",
				"uri": "spotify:album:3fsuoXmdJU3QLMNVucfQNE"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/1yz8XixOiIJJ9IxjbnfYV6"
					},
					"href": "https://api.spotify.com/v1/artists/1yz8XixOiIJJ9IxjbnfYV6",
					"id": "1yz8XixOiIJJ9IxjbnfYV6",
					"name": "NewDad",
					"type": "artist",
					"uri": "spotify:artist:1yz8XixOiIJJ9IxjbnfYV6"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 275013,
			"explicit": true,
			"external_ids": {
				"isrc": "GBKPL2031339"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/2W94sTwflT0Fg2tQc0vlfG"
			},
			"href": "https://api.spotify.com/v1/tracks/2W94sTwflT0Fg2tQc0vlfG",
			"id": "2W94sTwflT0Fg2tQc0vlfG",
			"is_local": false,
			"name": "I Don't Recognise You",
			"popularity": 54,
			"preview_url": "https://p.scdn.co/mp3-preview/2894a3cdfc781fca373d279d5f8e06276b7d403e?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 2,
			"type": "track",
			"uri": "spotify:track:2W94sTwflT0Fg2tQc0vlfG"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/7bQLFALIEawxhkyFiiLVhM"
						},
						"href": "https://api.spotify.com/v1/artists/7bQLFALIEawxhkyFiiLVhM",
						"id": "7bQLFALIEawxhkyFiiLVhM",
						"name": "Doss",
						"type": "artist",
						"uri": "spotify:artist:7bQLFALIEawxhkyFiiLVhM"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/5ip1HBRqhN4lzubgPiDNMt"
				},
				"href": "https://api.spotify.com/v1/albums/5ip1HBRqhN4lzubgPiDNMt",
				"id": "5ip1HBRqhN4lzubgPiDNMt",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b2738363ecde6e94b82d7b6ee8bc",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e028363ecde6e94b82d7b6ee8bc",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d000048518363ecde6e94b82d7b6ee8bc",
						"width": 64
					}
				],
				"name": "Strawberry",
				"release_date": "2021-04-21",
				"release_date_precision": "day",
				"total_tracks": 1,
				"type": "album",
				"uri": "spotify:album:5ip1HBRqhN4lzubgPiDNMt"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/7bQLFALIEawxhkyFiiLVhM"
					},
					"href": "https://api.spotify.com/v1/artists/7bQLFALIEawxhkyFiiLVhM",
					"id": "7bQLFALIEawxhkyFiiLVhM",
					"name": "Doss",
					"type": "artist",
					"uri": "spotify:artist:7bQLFALIEawxhkyFiiLVhM"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 209708,
			"explicit": false,
			"external_ids": {
				"isrc": "GB5P52100039"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/3FeiwCiTMUCh8h8G2T0Gmy"
			},
			"href": "https://api.spotify.com/v1/tracks/3FeiwCiTMUCh8h8G2T0Gmy",
			"id": "3FeiwCiTMUCh8h8G2T0Gmy",
			"is_local": false,
			"name": "Strawberry",
			"popularity": 48,
			"preview_url": "https://p.scdn.co/mp3-preview/bea88621792ade12f17b1127be1979960331a1dd?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:3FeiwCiTMUCh8h8G2T0Gmy"
		},
		{
			"album": {
				"album_type": "ALBUM",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/3zmfs9cQwzJl575W1ZYXeT"
						},
						"href": "https://api.spotify.com/v1/artists/3zmfs9cQwzJl575W1ZYXeT",
						"id": "3zmfs9cQwzJl575W1ZYXeT",
						"name": "Men I Trust",
						"type": "artist",
						"uri": "spotify:artist:3zmfs9cQwzJl575W1ZYXeT"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/7FkJxlcljM6Ix0pC2JSNOE"
				},
				"href": "https://api.spotify.com/v1/albums/7FkJxlcljM6Ix0pC2JSNOE",
				"id": "7FkJxlcljM6Ix0pC2JSNOE",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b273caa2063da9054f7b4e83f353",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e02caa2063da9054f7b4e83f353",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d00004851caa2063da9054f7b4e83f353",
						"width": 64
					}
				],
				"name": "Untourable Album",
				"release_date": "2021-08-25",
				"release_date_precision": "day",
				"total_tracks": 13,
				"type": "album",
				"uri": "spotify:album:7FkJxlcljM6Ix0pC2JSNOE"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/3zmfs9cQwzJl575W1ZYXeT"
					},
					"href": "https://api.spotify.com/v1/artists/3zmfs9cQwzJl575W1ZYXeT",
					"id": "3zmfs9cQwzJl575W1ZYXeT",
					"name": "Men I Trust",
					"type": "artist",
					"uri": "spotify:artist:3zmfs9cQwzJl575W1ZYXeT"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 183157,
			"explicit": false,
			"external_ids": {
				"isrc": "TCAFR2123401"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/7Ju5iOprgAdY8qimqzTwZR"
			},
			"href": "https://api.spotify.com/v1/tracks/7Ju5iOprgAdY8qimqzTwZR",
			"id": "7Ju5iOprgAdY8qimqzTwZR",
			"is_local": false,
			"name": "Lifelong Song",
			"popularity": 51,
			"preview_url": "https://p.scdn.co/mp3-preview/3d59d78b5c809d99df23f7f2074294632a28248b?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 11,
			"type": "track",
			"uri": "spotify:track:7Ju5iOprgAdY8qimqzTwZR"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/2mVVjNmdjXZZDvhgQWiakk"
						},
						"href": "https://api.spotify.com/v1/artists/2mVVjNmdjXZZDvhgQWiakk",
						"id": "2mVVjNmdjXZZDvhgQWiakk",
						"name": "Khruangbin",
						"type": "artist",
						"uri": "spotify:artist:2mVVjNmdjXZZDvhgQWiakk"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/2cvz3KTomD5JNGIBnCfiGD"
				},
				"href": "https://api.spotify.com/v1/albums/2cvz3KTomD5JNGIBnCfiGD",
				"id": "2cvz3KTomD5JNGIBnCfiGD",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b273e432b394b74ff2a4381f8957",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e02e432b394b74ff2a4381f8957",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d00004851e432b394b74ff2a4381f8957",
						"width": 64
					}
				],
				"name": "Pelota (Cut a Rug Mix)",
				"release_date": "2021-06-24",
				"release_date_precision": "day",
				"total_tracks": 2,
				"type": "album",
				"uri": "spotify:album:2cvz3KTomD5JNGIBnCfiGD"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/2mVVjNmdjXZZDvhgQWiakk"
					},
					"href": "https://api.spotify.com/v1/artists/2mVVjNmdjXZZDvhgQWiakk",
					"id": "2mVVjNmdjXZZDvhgQWiakk",
					"name": "Khruangbin",
					"type": "artist",
					"uri": "spotify:artist:2mVVjNmdjXZZDvhgQWiakk"
				},
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/5ZMwoAjeDtLJ0XRwRTgaK8"
					},
					"href": "https://api.spotify.com/v1/artists/5ZMwoAjeDtLJ0XRwRTgaK8",
					"id": "5ZMwoAjeDtLJ0XRwRTgaK8",
					"name": "Quantic",
					"type": "artist",
					"uri": "spotify:artist:5ZMwoAjeDtLJ0XRwRTgaK8"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 301995,
			"explicit": false,
			"external_ids": {
				"isrc": "USJ5G2023006"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/380cW88WvjXFmX3wzK1NOf"
			},
			"href": "https://api.spotify.com/v1/tracks/380cW88WvjXFmX3wzK1NOf",
			"id": "380cW88WvjXFmX3wzK1NOf",
			"is_local": false,
			"name": "Pelota (Cut a Rug Mix)",
			"popularity": 52,
			"preview_url": "https://p.scdn.co/mp3-preview/c3eb7c8623e34716fcf088f6a5b49d64d6d2b1ad?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:380cW88WvjXFmX3wzK1NOf"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/7hccrx4H5boJlleSXh1j7N"
						},
						"href": "https://api.spotify.com/v1/artists/7hccrx4H5boJlleSXh1j7N",
						"id": "7hccrx4H5boJlleSXh1j7N",
						"name": "Johan Vilborg",
						"type": "artist",
						"uri": "spotify:artist:7hccrx4H5boJlleSXh1j7N"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/2zUK6Hc9NT0j62AExc6riK"
				},
				"href": "https://api.spotify.com/v1/albums/2zUK6Hc9NT0j62AExc6riK",
				"id": "2zUK6Hc9NT0j62AExc6riK",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b273e958af9b4267e13d48f27ffa",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e02e958af9b4267e13d48f27ffa",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d00004851e958af9b4267e13d48f27ffa",
						"width": 64
					}
				],
				"name": "Altara",
				"release_date": "2012-01-10",
				"release_date_precision": "day",
				"total_tracks": 3,
				"type": "album",
				"uri": "spotify:album:2zUK6Hc9NT0j62AExc6riK"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/7hccrx4H5boJlleSXh1j7N"
					},
					"href": "https://api.spotify.com/v1/artists/7hccrx4H5boJlleSXh1j7N",
					"id": "7hccrx4H5boJlleSXh1j7N",
					"name": "Johan Vilborg",
					"type": "artist",
					"uri": "spotify:artist:7hccrx4H5boJlleSXh1j7N"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 422000,
			"explicit": false,
			"external_ids": {
				"isrc": "US83Z1109121"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/5I6WLOIu8CjdFMY3ojDzIS"
			},
			"href": "https://api.spotify.com/v1/tracks/5I6WLOIu8CjdFMY3ojDzIS",
			"id": "5I6WLOIu8CjdFMY3ojDzIS",
			"is_local": false,
			"name": "Altara",
			"popularity": 23,
			"preview_url": "https://p.scdn.co/mp3-preview/6d4eef794bffc3e2b1d1b0e1ceaefadbe12b25d2?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:5I6WLOIu8CjdFMY3ojDzIS"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/3IunaFjvNKj98JW89JYv9u"
						},
						"href": "https://api.spotify.com/v1/artists/3IunaFjvNKj98JW89JYv9u",
						"id": "3IunaFjvNKj98JW89JYv9u",
						"name": "The Japanese House",
						"type": "artist",
						"uri": "spotify:artist:3IunaFjvNKj98JW89JYv9u"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/1OlByJ5jsP9Eklfp03Xn8z"
				},
				"href": "https://api.spotify.com/v1/albums/1OlByJ5jsP9Eklfp03Xn8z",
				"id": "1OlByJ5jsP9Eklfp03Xn8z",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b2738935646998a8d28d13bc348d",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e028935646998a8d28d13bc348d",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d000048518935646998a8d28d13bc348d",
						"width": 64
					}
				],
				"name": "Chewing Cotton Wool",
				"release_date": "2020-08-12",
				"release_date_precision": "day",
				"total_tracks": 4,
				"type": "album",
				"uri": "spotify:album:1OlByJ5jsP9Eklfp03Xn8z"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/3IunaFjvNKj98JW89JYv9u"
					},
					"href": "https://api.spotify.com/v1/artists/3IunaFjvNKj98JW89JYv9u",
					"id": "3IunaFjvNKj98JW89JYv9u",
					"name": "The Japanese House",
					"type": "artist",
					"uri": "spotify:artist:3IunaFjvNKj98JW89JYv9u"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 191200,
			"explicit": false,
			"external_ids": {
				"isrc": "GBK3W1901155"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/2KWI43agrQEFVLM3soOmKW"
			},
			"href": "https://api.spotify.com/v1/tracks/2KWI43agrQEFVLM3soOmKW",
			"id": "2KWI43agrQEFVLM3soOmKW",
			"is_local": false,
			"name": "Something Has to Change",
			"popularity": 58,
			"preview_url": "https://p.scdn.co/mp3-preview/8be1e161a30293f6d4e663e372682cb7897c0028?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 2,
			"type": "track",
			"uri": "spotify:track:2KWI43agrQEFVLM3soOmKW"
		},
		{
			"album": {
				"album_type": "ALBUM",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/6TTJ0xLPPNDyv4bXyukzU4"
						},
						"href": "https://api.spotify.com/v1/artists/6TTJ0xLPPNDyv4bXyukzU4",
						"id": "6TTJ0xLPPNDyv4bXyukzU4",
						"name": "Sam Amidon",
						"type": "artist",
						"uri": "spotify:artist:6TTJ0xLPPNDyv4bXyukzU4"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/1Jk12pD1RaSl1SM9Ig5X8m"
				},
				"href": "https://api.spotify.com/v1/albums/1Jk12pD1RaSl1SM9Ig5X8m",
				"id": "1Jk12pD1RaSl1SM9Ig5X8m",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b27301982d709379d6218c62c093",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e0201982d709379d6218c62c093",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d0000485101982d709379d6218c62c093",
						"width": 64
					}
				],
				"name": "Sam Amidon",
				"release_date": "2020-10-23",
				"release_date_precision": "day",
				"total_tracks": 9,
				"type": "album",
				"uri": "spotify:album:1Jk12pD1RaSl1SM9Ig5X8m"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/6TTJ0xLPPNDyv4bXyukzU4"
					},
					"href": "https://api.spotify.com/v1/artists/6TTJ0xLPPNDyv4bXyukzU4",
					"id": "6TTJ0xLPPNDyv4bXyukzU4",
					"name": "Sam Amidon",
					"type": "artist",
					"uri": "spotify:artist:6TTJ0xLPPNDyv4bXyukzU4"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 294360,
			"explicit": false,
			"external_ids": {
				"isrc": "USNO12000184"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/00DyyDxPVjFdtLILeZsxjv"
			},
			"href": "https://api.spotify.com/v1/tracks/00DyyDxPVjFdtLILeZsxjv",
			"id": "00DyyDxPVjFdtLILeZsxjv",
			"is_local": false,
			"name": "Maggie",
			"popularity": 35,
			"preview_url": "https://p.scdn.co/mp3-preview/1527133ce71187172ec8cf0f192e169897fb650f?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:00DyyDxPVjFdtLILeZsxjv"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/4GoD5FJCgC0lbzde7ly44M"
						},
						"href": "https://api.spotify.com/v1/artists/4GoD5FJCgC0lbzde7ly44M",
						"id": "4GoD5FJCgC0lbzde7ly44M",
						"name": "Biig Piig",
						"type": "artist",
						"uri": "spotify:artist:4GoD5FJCgC0lbzde7ly44M"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/1Uo1xB5dmrRWnhuouxDRib"
				},
				"href": "https://api.spotify.com/v1/albums/1Uo1xB5dmrRWnhuouxDRib",
				"id": "1Uo1xB5dmrRWnhuouxDRib",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b2732d9c59c68cc0a8f666cbeeaf",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e022d9c59c68cc0a8f666cbeeaf",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d000048512d9c59c68cc0a8f666cbeeaf",
						"width": 64
					}
				],
				"name": "The Sky Is Bleeding",
				"release_date": "2021-05-21",
				"release_date_precision": "day",
				"total_tracks": 6,
				"type": "album",
				"uri": "spotify:album:1Uo1xB5dmrRWnhuouxDRib"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/4GoD5FJCgC0lbzde7ly44M"
					},
					"href": "https://api.spotify.com/v1/artists/4GoD5FJCgC0lbzde7ly44M",
					"id": "4GoD5FJCgC0lbzde7ly44M",
					"name": "Biig Piig",
					"type": "artist",
					"uri": "spotify:artist:4GoD5FJCgC0lbzde7ly44M"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 172066,
			"explicit": false,
			"external_ids": {
				"isrc": "GBARL2100319"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/5sd5iSdc2bRXGirMiBcMDb"
			},
			"href": "https://api.spotify.com/v1/tracks/5sd5iSdc2bRXGirMiBcMDb",
			"id": "5sd5iSdc2bRXGirMiBcMDb",
			"is_local": false,
			"name": "American Beauty",
			"popularity": 51,
			"preview_url": "https://p.scdn.co/mp3-preview/d393acee2eba827e27990ef21fe63c16a31909b6?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 6,
			"type": "track",
			"uri": "spotify:track:5sd5iSdc2bRXGirMiBcMDb"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/54QMjE4toDfiCryzYWCpXX"
						},
						"href": "https://api.spotify.com/v1/artists/54QMjE4toDfiCryzYWCpXX",
						"id": "54QMjE4toDfiCryzYWCpXX",
						"name": "Metronomy",
						"type": "artist",
						"uri": "spotify:artist:54QMjE4toDfiCryzYWCpXX"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/23DeMPTDoiswc4O9Ipyubh"
				},
				"href": "https://api.spotify.com/v1/albums/23DeMPTDoiswc4O9Ipyubh",
				"id": "23DeMPTDoiswc4O9Ipyubh",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b2732398848f8ee02618599fdc8f",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e022398848f8ee02618599fdc8f",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d000048512398848f8ee02618599fdc8f",
						"width": 64
					}
				],
				"name": "Posse EP Volume 1",
				"release_date": "2021-09-15",
				"release_date_precision": "day",
				"total_tracks": 5,
				"type": "album",
				"uri": "spotify:album:23DeMPTDoiswc4O9Ipyubh"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/54QMjE4toDfiCryzYWCpXX"
					},
					"href": "https://api.spotify.com/v1/artists/54QMjE4toDfiCryzYWCpXX",
					"id": "54QMjE4toDfiCryzYWCpXX",
					"name": "Metronomy",
					"type": "artist",
					"uri": "spotify:artist:54QMjE4toDfiCryzYWCpXX"
				},
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/5RpQGZtxRWXdEZpV7gNdvM"
					},
					"href": "https://api.spotify.com/v1/artists/5RpQGZtxRWXdEZpV7gNdvM",
					"id": "5RpQGZtxRWXdEZpV7gNdvM",
					"name": "Brian Nasty",
					"type": "artist",
					"uri": "spotify:artist:5RpQGZtxRWXdEZpV7gNdvM"
				},
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/39RnqcMpFSK4e7tbODSsaP"
					},
					"href": "https://api.spotify.com/v1/artists/39RnqcMpFSK4e7tbODSsaP",
					"id": "39RnqcMpFSK4e7tbODSsaP",
					"name": "Folly Group",
					"type": "artist",
					"uri": "spotify:artist:39RnqcMpFSK4e7tbODSsaP"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 240890,
			"explicit": false,
			"external_ids": {
				"isrc": "GBMVH2100790"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/3uge0EpDZWUEQwJk4jW5rI"
			},
			"href": "https://api.spotify.com/v1/tracks/3uge0EpDZWUEQwJk4jW5rI",
			"id": "3uge0EpDZWUEQwJk4jW5rI",
			"is_local": false,
			"name": "Monday - Metronomy x Brian Nasty x Folly Group",
			"popularity": 38,
			"preview_url": "https://p.scdn.co/mp3-preview/4e4ab4d709ed0c213854e822a48fba60f0247cd5?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 5,
			"type": "track",
			"uri": "spotify:track:3uge0EpDZWUEQwJk4jW5rI"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/1np8xozf7ATJZDi9JX8Dx5"
						},
						"href": "https://api.spotify.com/v1/artists/1np8xozf7ATJZDi9JX8Dx5",
						"id": "1np8xozf7ATJZDi9JX8Dx5",
						"name": "salute",
						"type": "artist",
						"uri": "spotify:artist:1np8xozf7ATJZDi9JX8Dx5"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/4nbLoYqrWa7FZ6v0Cvp6Jq"
				},
				"href": "https://api.spotify.com/v1/albums/4nbLoYqrWa7FZ6v0Cvp6Jq",
				"id": "4nbLoYqrWa7FZ6v0Cvp6Jq",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b273567b716730d4ffa212e0ff3c",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e02567b716730d4ffa212e0ff3c",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d00004851567b716730d4ffa212e0ff3c",
						"width": 64
					}
				],
				"name": "Want U There",
				"release_date": "2021-04-30",
				"release_date_precision": "day",
				"total_tracks": 2,
				"type": "album",
				"uri": "spotify:album:4nbLoYqrWa7FZ6v0Cvp6Jq"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/1np8xozf7ATJZDi9JX8Dx5"
					},
					"href": "https://api.spotify.com/v1/artists/1np8xozf7ATJZDi9JX8Dx5",
					"id": "1np8xozf7ATJZDi9JX8Dx5",
					"name": "salute",
					"type": "artist",
					"uri": "spotify:artist:1np8xozf7ATJZDi9JX8Dx5"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 176506,
			"explicit": false,
			"external_ids": {
				"isrc": "GBX722100180"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/6bgUfXTnC8XCnsTkiucJtD"
			},
			"href": "https://api.spotify.com/v1/tracks/6bgUfXTnC8XCnsTkiucJtD",
			"id": "6bgUfXTnC8XCnsTkiucJtD",
			"is_local": false,
			"name": "Want U There",
			"popularity": 44,
			"preview_url": "https://p.scdn.co/mp3-preview/65184ea33fc40f95976cc25211264bb7b7941393?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:6bgUfXTnC8XCnsTkiucJtD"
		},
		{
			"album": {
				"album_type": "COMPILATION",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
						},
						"href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
						"id": "0LyfQWJT6nXafLPZqxe9Of",
						"name": "Various Artists",
						"type": "artist",
						"uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/48bHtfplT0v7mdakwN6Eu2"
				},
				"href": "https://api.spotify.com/v1/albums/48bHtfplT0v7mdakwN6Eu2",
				"id": "48bHtfplT0v7mdakwN6Eu2",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b273a1ed7c3e9f2884fee6593f25",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e02a1ed7c3e9f2884fee6593f25",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d00004851a1ed7c3e9f2884fee6593f25",
						"width": 64
					}
				],
				"name": "Erased Tapes Collection VIII",
				"release_date": "2017-02-05",
				"release_date_precision": "day",
				"total_tracks": 11,
				"type": "album",
				"uri": "spotify:album:48bHtfplT0v7mdakwN6Eu2"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/7E3BRXV9ZbCt5lQTCXMTia"
					},
					"href": "https://api.spotify.com/v1/artists/7E3BRXV9ZbCt5lQTCXMTia",
					"id": "7E3BRXV9ZbCt5lQTCXMTia",
					"name": "Ólafur Arnalds",
					"type": "artist",
					"uri": "spotify:artist:7E3BRXV9ZbCt5lQTCXMTia"
				},
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/5gqhueRUZEa7VDnQt4HODp"
					},
					"href": "https://api.spotify.com/v1/artists/5gqhueRUZEa7VDnQt4HODp",
					"id": "5gqhueRUZEa7VDnQt4HODp",
					"name": "Nils Frahm",
					"type": "artist",
					"uri": "spotify:artist:5gqhueRUZEa7VDnQt4HODp"
				},
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/0AHClmU8AZuj9naaENhVrP"
					},
					"href": "https://api.spotify.com/v1/artists/0AHClmU8AZuj9naaENhVrP",
					"id": "0AHClmU8AZuj9naaENhVrP",
					"name": "Ryan Davis",
					"type": "artist",
					"uri": "spotify:artist:0AHClmU8AZuj9naaENhVrP"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 327430,
			"explicit": false,
			"external_ids": {
				"isrc": "GBWZD1708007"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/4x2giD44A8wYVzf28v5bT2"
			},
			"href": "https://api.spotify.com/v1/tracks/4x2giD44A8wYVzf28v5bT2",
			"id": "4x2giD44A8wYVzf28v5bT2",
			"is_local": false,
			"name": "00:26 - Ryan Davis Rethink",
			"popularity": 12,
			"preview_url": "https://p.scdn.co/mp3-preview/0f17b2d25646239d3ffb7441c3da4507c78c4aee?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 7,
			"type": "track",
			"uri": "spotify:track:4x2giD44A8wYVzf28v5bT2"
		},
		{
			"album": {
				"album_type": "ALBUM",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/1kR99O4MgSTasyeJh8UFCg"
						},
						"href": "https://api.spotify.com/v1/artists/1kR99O4MgSTasyeJh8UFCg",
						"id": "1kR99O4MgSTasyeJh8UFCg",
						"name": "DJ Koze",
						"type": "artist",
						"uri": "spotify:artist:1kR99O4MgSTasyeJh8UFCg"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/0sT4nyNxsvGNQr1O8OR83O"
				},
				"href": "https://api.spotify.com/v1/albums/0sT4nyNxsvGNQr1O8OR83O",
				"id": "0sT4nyNxsvGNQr1O8OR83O",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b2737a4ffc6739a18161ddf02826",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e027a4ffc6739a18161ddf02826",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d000048517a4ffc6739a18161ddf02826",
						"width": 64
					}
				],
				"name": "Knock Knock",
				"release_date": "2018-05-04",
				"release_date_precision": "day",
				"total_tracks": 16,
				"type": "album",
				"uri": "spotify:album:0sT4nyNxsvGNQr1O8OR83O"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/1kR99O4MgSTasyeJh8UFCg"
					},
					"href": "https://api.spotify.com/v1/artists/1kR99O4MgSTasyeJh8UFCg",
					"id": "1kR99O4MgSTasyeJh8UFCg",
					"name": "DJ Koze",
					"type": "artist",
					"uri": "spotify:artist:1kR99O4MgSTasyeJh8UFCg"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 398150,
			"explicit": false,
			"external_ids": {
				"isrc": "DEMM11800008"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/5YzBL3vkQnp3JbeDRRSbSQ"
			},
			"href": "https://api.spotify.com/v1/tracks/5YzBL3vkQnp3JbeDRRSbSQ",
			"id": "5YzBL3vkQnp3JbeDRRSbSQ",
			"is_local": false,
			"name": "Pick Up",
			"popularity": 57,
			"preview_url": "https://p.scdn.co/mp3-preview/59df04ae26c0cb6088fc0998d62c7764ca70c9c3?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 8,
			"type": "track",
			"uri": "spotify:track:5YzBL3vkQnp3JbeDRRSbSQ"
		},
		{
			"album": {
				"album_type": "ALBUM",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/0ygIgsjUzKivFgxgjQ9iV9"
						},
						"href": "https://api.spotify.com/v1/artists/0ygIgsjUzKivFgxgjQ9iV9",
						"id": "0ygIgsjUzKivFgxgjQ9iV9",
						"name": "Jacques Greene",
						"type": "artist",
						"uri": "spotify:artist:0ygIgsjUzKivFgxgjQ9iV9"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/5ZscjYDLx3luVuDWPMkT3x"
				},
				"href": "https://api.spotify.com/v1/albums/5ZscjYDLx3luVuDWPMkT3x",
				"id": "5ZscjYDLx3luVuDWPMkT3x",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b27330bfa8bba270ef6254db1b94",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e0230bfa8bba270ef6254db1b94",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d0000485130bfa8bba270ef6254db1b94",
						"width": 64
					}
				],
				"name": "ANTH01",
				"release_date": "2021-10-22",
				"release_date_precision": "day",
				"total_tracks": 12,
				"type": "album",
				"uri": "spotify:album:5ZscjYDLx3luVuDWPMkT3x"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/0ygIgsjUzKivFgxgjQ9iV9"
					},
					"href": "https://api.spotify.com/v1/artists/0ygIgsjUzKivFgxgjQ9iV9",
					"id": "0ygIgsjUzKivFgxgjQ9iV9",
					"name": "Jacques Greene",
					"type": "artist",
					"uri": "spotify:artist:0ygIgsjUzKivFgxgjQ9iV9"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 403080,
			"explicit": false,
			"external_ids": {
				"isrc": "USYBL1002609"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/0GREcaqrfl68u5hW5FeL8p"
			},
			"href": "https://api.spotify.com/v1/tracks/0GREcaqrfl68u5hW5FeL8p",
			"id": "0GREcaqrfl68u5hW5FeL8p",
			"is_local": false,
			"name": "Another Girl",
			"popularity": 39,
			"preview_url": "https://p.scdn.co/mp3-preview/c1f6afc4aa8081f6154dc04a56f40392fe91aa2c?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 12,
			"type": "track",
			"uri": "spotify:track:0GREcaqrfl68u5hW5FeL8p"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/47sKkybVg9NVz7IWvTezzy"
						},
						"href": "https://api.spotify.com/v1/artists/47sKkybVg9NVz7IWvTezzy",
						"id": "47sKkybVg9NVz7IWvTezzy",
						"name": "TAXI KEBAB",
						"type": "artist",
						"uri": "spotify:artist:47sKkybVg9NVz7IWvTezzy"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/6T5BcuQisJcN2E4O6BmRDk"
				},
				"href": "https://api.spotify.com/v1/albums/6T5BcuQisJcN2E4O6BmRDk",
				"id": "6T5BcuQisJcN2E4O6BmRDk",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b2730f269e8f55d61fda2cd6006e",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e020f269e8f55d61fda2cd6006e",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d000048510f269e8f55d61fda2cd6006e",
						"width": 64
					}
				],
				"name": "Lmchi w Rjou3",
				"release_date": "2019-05-21",
				"release_date_precision": "day",
				"total_tracks": 1,
				"type": "album",
				"uri": "spotify:album:6T5BcuQisJcN2E4O6BmRDk"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/47sKkybVg9NVz7IWvTezzy"
					},
					"href": "https://api.spotify.com/v1/artists/47sKkybVg9NVz7IWvTezzy",
					"id": "47sKkybVg9NVz7IWvTezzy",
					"name": "TAXI KEBAB",
					"type": "artist",
					"uri": "spotify:artist:47sKkybVg9NVz7IWvTezzy"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 385253,
			"explicit": false,
			"external_ids": {
				"isrc": "TCAEF1966181"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/25NuCWQ4cIxmwxRHMZ0C4L"
			},
			"href": "https://api.spotify.com/v1/tracks/25NuCWQ4cIxmwxRHMZ0C4L",
			"id": "25NuCWQ4cIxmwxRHMZ0C4L",
			"is_local": false,
			"name": "Lmchi w Rjou3",
			"popularity": 40,
			"preview_url": "https://p.scdn.co/mp3-preview/a7f4c66f4fc53f29c4d45eed466cded0f0e89ca0?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:25NuCWQ4cIxmwxRHMZ0C4L"
		},
		{
			"album": {
				"album_type": "ALBUM",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/5MaQlvNGOaTj39apHsXVq1"
						},
						"href": "https://api.spotify.com/v1/artists/5MaQlvNGOaTj39apHsXVq1",
						"id": "5MaQlvNGOaTj39apHsXVq1",
						"name": "Claud",
						"type": "artist",
						"uri": "spotify:artist:5MaQlvNGOaTj39apHsXVq1"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/0QPFWBu8oVVNtekmNzlVvW"
				},
				"href": "https://api.spotify.com/v1/albums/0QPFWBu8oVVNtekmNzlVvW",
				"id": "0QPFWBu8oVVNtekmNzlVvW",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b273980bcb64e708dcff98093cdf",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e02980bcb64e708dcff98093cdf",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d00004851980bcb64e708dcff98093cdf",
						"width": 64
					}
				],
				"name": "Super Monster",
				"release_date": "2021-02-12",
				"release_date_precision": "day",
				"total_tracks": 13,
				"type": "album",
				"uri": "spotify:album:0QPFWBu8oVVNtekmNzlVvW"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/5MaQlvNGOaTj39apHsXVq1"
					},
					"href": "https://api.spotify.com/v1/artists/5MaQlvNGOaTj39apHsXVq1",
					"id": "5MaQlvNGOaTj39apHsXVq1",
					"name": "Claud",
					"type": "artist",
					"uri": "spotify:artist:5MaQlvNGOaTj39apHsXVq1"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 188097,
			"explicit": false,
			"external_ids": {
				"isrc": "USJ5G2000103"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/30bqNfOgcJOw2EWJJl1w5J"
			},
			"href": "https://api.spotify.com/v1/tracks/30bqNfOgcJOw2EWJJl1w5J",
			"id": "30bqNfOgcJOw2EWJJl1w5J",
			"is_local": false,
			"name": "Soft Spot",
			"popularity": 59,
			"preview_url": "https://p.scdn.co/mp3-preview/91385348a78dc5208e39ad88c7212810d68c18f3?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 3,
			"type": "track",
			"uri": "spotify:track:30bqNfOgcJOw2EWJJl1w5J"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/3jEWwtiifaWzV7ZcRduuxU"
						},
						"href": "https://api.spotify.com/v1/artists/3jEWwtiifaWzV7ZcRduuxU",
						"id": "3jEWwtiifaWzV7ZcRduuxU",
						"name": "Dinka",
						"type": "artist",
						"uri": "spotify:artist:3jEWwtiifaWzV7ZcRduuxU"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/3k4d5eCa3R5XXK6w1FyfEW"
				},
				"href": "https://api.spotify.com/v1/albums/3k4d5eCa3R5XXK6w1FyfEW",
				"id": "3k4d5eCa3R5XXK6w1FyfEW",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b2737d779cce0b0e85ca4fecbd5c",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e027d779cce0b0e85ca4fecbd5c",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d000048517d779cce0b0e85ca4fecbd5c",
						"width": 64
					}
				],
				"name": "Lotus",
				"release_date": "2012-09-11",
				"release_date_precision": "day",
				"total_tracks": 3,
				"type": "album",
				"uri": "spotify:album:3k4d5eCa3R5XXK6w1FyfEW"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/3jEWwtiifaWzV7ZcRduuxU"
					},
					"href": "https://api.spotify.com/v1/artists/3jEWwtiifaWzV7ZcRduuxU",
					"id": "3jEWwtiifaWzV7ZcRduuxU",
					"name": "Dinka",
					"type": "artist",
					"uri": "spotify:artist:3jEWwtiifaWzV7ZcRduuxU"
				},
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/7hccrx4H5boJlleSXh1j7N"
					},
					"href": "https://api.spotify.com/v1/artists/7hccrx4H5boJlleSXh1j7N",
					"id": "7hccrx4H5boJlleSXh1j7N",
					"name": "Johan Vilborg",
					"type": "artist",
					"uri": "spotify:artist:7hccrx4H5boJlleSXh1j7N"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 449997,
			"explicit": false,
			"external_ids": {
				"isrc": "US83Z1207582"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/0ZPfrTK4bjEkDE7Nr90325"
			},
			"href": "https://api.spotify.com/v1/tracks/0ZPfrTK4bjEkDE7Nr90325",
			"id": "0ZPfrTK4bjEkDE7Nr90325",
			"is_local": false,
			"name": "Lotus - Johan Vilborg Remix",
			"popularity": 32,
			"preview_url": "https://p.scdn.co/mp3-preview/b5c4185c287db385a4ddd31b6f9cc0a466799943?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 3,
			"type": "track",
			"uri": "spotify:track:0ZPfrTK4bjEkDE7Nr90325"
		},
		{
			"album": {
				"album_type": "COMPILATION",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/40Yq4vzPs9VNUrIBG5Jr2i"
						},
						"href": "https://api.spotify.com/v1/artists/40Yq4vzPs9VNUrIBG5Jr2i",
						"id": "40Yq4vzPs9VNUrIBG5Jr2i",
						"name": "The Smashing Pumpkins",
						"type": "artist",
						"uri": "spotify:artist:40Yq4vzPs9VNUrIBG5Jr2i"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/1cUnNrx2TxvrpwPRtvpGwn"
				},
				"href": "https://api.spotify.com/v1/albums/1cUnNrx2TxvrpwPRtvpGwn",
				"id": "1cUnNrx2TxvrpwPRtvpGwn",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b273c48f42fdafcffcedbdbce025",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e02c48f42fdafcffcedbdbce025",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d00004851c48f42fdafcffcedbdbce025",
						"width": 64
					}
				],
				"name": "(Rotten Apples) The Smashing Pumpkins Greatest Hits",
				"release_date": "2001-01-01",
				"release_date_precision": "day",
				"total_tracks": 18,
				"type": "album",
				"uri": "spotify:album:1cUnNrx2TxvrpwPRtvpGwn"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/40Yq4vzPs9VNUrIBG5Jr2i"
					},
					"href": "https://api.spotify.com/v1/artists/40Yq4vzPs9VNUrIBG5Jr2i",
					"id": "40Yq4vzPs9VNUrIBG5Jr2i",
					"name": "The Smashing Pumpkins",
					"type": "artist",
					"uri": "spotify:artist:40Yq4vzPs9VNUrIBG5Jr2i"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 270400,
			"explicit": false,
			"external_ids": {
				"isrc": "USSM19200933"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/3eMYc6FK9XvyauIaxcJtRS"
			},
			"href": "https://api.spotify.com/v1/tracks/3eMYc6FK9XvyauIaxcJtRS",
			"id": "3eMYc6FK9XvyauIaxcJtRS",
			"is_local": false,
			"name": "Drown",
			"popularity": 63,
			"preview_url": "https://p.scdn.co/mp3-preview/37ca1c4959eff687a30b168cd43c70342e8a9360?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 3,
			"type": "track",
			"uri": "spotify:track:3eMYc6FK9XvyauIaxcJtRS"
		},
		{
			"album": {
				"album_type": "SINGLE",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/67YkGjtw8rmC6Ck0GmoxFA"
						},
						"href": "https://api.spotify.com/v1/artists/67YkGjtw8rmC6Ck0GmoxFA",
						"id": "67YkGjtw8rmC6Ck0GmoxFA",
						"name": "Dj Streaks",
						"type": "artist",
						"uri": "spotify:artist:67YkGjtw8rmC6Ck0GmoxFA"
					}
				],
				"available_markets": [
					"AD",
					"AE",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BH",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"DZ",
					"EC",
					"EE",
					"EG",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IN",
					"IS",
					"IT",
					"JO",
					"JP",
					"KW",
					"LB",
					"LI",
					"LT",
					"LU",
					"LV",
					"MA",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"OM",
					"PA",
					"PE",
					"PH",
					"PL",
					"PS",
					"PT",
					"PY",
					"QA",
					"RO",
					"SA",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TN",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/1afYraZZkxPQTTkvVVHc4r"
				},
				"href": "https://api.spotify.com/v1/albums/1afYraZZkxPQTTkvVVHc4r",
				"id": "1afYraZZkxPQTTkvVVHc4r",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/ab67616d0000b273d500775f0656f0a568afef66",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/ab67616d00001e02d500775f0656f0a568afef66",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/ab67616d00004851d500775f0656f0a568afef66",
						"width": 64
					}
				],
				"name": "Greatest Love",
				"release_date": "2020-07-10",
				"release_date_precision": "day",
				"total_tracks": 2,
				"type": "album",
				"uri": "spotify:album:1afYraZZkxPQTTkvVVHc4r"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/67YkGjtw8rmC6Ck0GmoxFA"
					},
					"href": "https://api.spotify.com/v1/artists/67YkGjtw8rmC6Ck0GmoxFA",
					"id": "67YkGjtw8rmC6Ck0GmoxFA",
					"name": "Dj Streaks",
					"type": "artist",
					"uri": "spotify:artist:67YkGjtw8rmC6Ck0GmoxFA"
				}
			],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 230551,
			"explicit": false,
			"external_ids": {
				"isrc": "FRX202041472"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/6wmtEikDlY2JbV0nlrscxy"
			},
			"href": "https://api.spotify.com/v1/tracks/6wmtEikDlY2JbV0nlrscxy",
			"id": "6wmtEikDlY2JbV0nlrscxy",
			"is_local": false,
			"name": "Greatest Love - Edit",
			"popularity": 52,
			"preview_url": "https://p.scdn.co/mp3-preview/ae9a80893cf6e47864ba83b34bb3220c02bb115e?cid=b997a3c051c84b9484b3afcbf6604a9a",
			"track_number": 2,
			"type": "track",
			"uri": "spotify:track:6wmtEikDlY2JbV0nlrscxy"
		}
	],
	"total": 50,
	"limit": 20,
	"offset": 0,
	"href": "https://api.spotify.com/v1/me/top/tracks",
	"previous": null,
	"next": "https://api.spotify.com/v1/me/top/tracks?limit=20&offset=20"
}